packages:
  - tools/**
  - packages/**
  - apps/cores/**
  - apps/users/**
  - apps/managers/**

exclude:
  - "**/dist/**"
  - "**/node_modules/**"
  - "**/coverage/**"
  - "**/build/**"

catalog:
  "@biomejs/biome": ^1.9.4
  "@grpc/grpc-js": ^1.12.2
  "@tsconfig/strictest": ^2.0.5
  "@types/node": ^22.7.3
  "@vitest/coverage-v8": "^2.1.1"
  husky: ^9.1.6
  nice-grpc-common: ^2.0.2
  nice-grpc: ^2.1.10
  tsx: ^4.19.1
  typescript: ^5.6.2
  unplugin-swc: ^1.5.1
  vitest: ^2.1.1
